#!/bin/bash

set -x

GAUNTLET_HOST=localhost

status=eval $@
echo "status = $?"

curl -X POST -d "{'pipeline':$GO_PIPELINE_NAME, 'pipecount':$GO_PIPELINE_COUNTER, 'stage':$GO_STAGE_NAME, 'stagecount':$GO_STAGE_COUNTER, 'jobname':$GO_JOB_NAME, 'gitinfo': $GO_REVISION}"  ${GAUNTLET_HOST}/result

exit $status
